### ISSUE TITLE
RSS订阅功能

### ISSUE THREAD

**Issue by vincent4j** [larryzhao/jianshu.io#1]
**需求**
前段时间刚刚上线“关注动态”的功能，已经比较好。但有一点，还是得用户主动去关注（进入到jianshu.io），我个人更喜欢RSS订阅，直接、明了。

**弊端**
从流量方面考虑，可能带走一部分简书原本的流量，即流量分散。

**Comment by larryzhao** [comment]
已经在做了哈 :)

**Comment by vincent4j** [comment]
@larryzhao  恩，先前就知道这消息；add issue只是为了捧场，haha。
