### ISSUE TITLE
Markdown img 标签解析问题

### ISSUE THREAD

**Issue by rainyear** [larryzhao/jianshu.io#10]
md的img标签语法为`![](src)`，但是当src的url存在闭合括号时似乎会与标签的括号产生冲突（至少在预览模式下是有问题的），例如：
`![](http://latex.codecogs.com/gif.latex?\prod%20(n_{i})+1)`
将显示为<img src=http://latex.codecogs.com/gif.latex?\prod%20(n_{i} />+1)，当然如果是用urlencode过的src是没有问题的，但是链接太难看无法接受，最后用img标签硬编码解决的。

---

竟然发现github也不支持这样的格式，难道是我太吹毛求疵了。。。-_-!

**Comment by larryzhao** [comment]
这个之前还真没想到过, 我去研究研究. Github因为也不是写科学文献相关的, 所以就没有吧。

我们应该可以尝试对所有的都做urlencode, 另外这是一个image, 链接太难看会有啥问题么? 链接正常情况应该是不显示的吧..?

**Comment by rainyear** [comment]
因为是通过url参数中的LaTeX公式生成的图片，所以urlencode之后公式就完全看不出来了...写草稿的时候还是能看到公式比较舒服

**Comment by larryzhao** [comment]
Hi, 我稍微研究了一下, 可以用间接指明 src url的方式来做, 跟link一样, 

按照这样写: https://gist.github.com/larryzhao/5901059
(评论里因为是markdown的, 我死活写不出来, 就算包在代码段里也不行, 还是点去看 gist 吧.)

这里是结果:
http://jianshu.io/p/R5nTSR

**Comment by rainyear** [comment]
cool!

**Comment by larryzhao** [comment]
感觉我们还是给他加了个边框不太对

**Comment by larryzhao** [comment]
看了一下, 我们现在从全站角度考虑还是不能去掉图片上的边框, 你在这里只能暂时直接使用 `<a>` tag来写了.
