### ISSUE TITLE
写作界面下笔记条目操作按钮过于不明显

### ISSUE THREAD

**Issue by VirgilMing** [larryzhao/jianshu.io#11]
如图，旁边那两个按钮略反人类……
![image](https://f.cloud.github.com/assets/3634358/737828/9ee28f0e-e337-11e2-8660-2b5dac41d873.png)

**Comment by larryzhao** [comment]
...你这个是个错误情况, 正常情况应该是这样的:
![screen shot 2013-07-03 at 09 52 11](https://f.cloud.github.com/assets/442278/740718/46e37bb4-e383-11e2-91e4-109acd37796e.png)

你一直看到的是白的么?

**Comment by VirgilMing** [comment]
今天好了，不知道怎么回事……

补充下环境，Chrome 27 @ Windows 7 64-bit SP1。当时只开了两个文档，换来换去都那样。
