### ISSUE TITLE
ipad上使用safari和UC浏览器均不能使用新浪微博登录

### ISSUE THREAD

**Issue by yangwenmai** [larryzhao/jianshu.io#17]

**Comment by larryzhao** [comment]
我们这里试验可以诶, 能具体描述一下么

**Comment by yangwenmai** [comment]
我是使用的ipad mini

**Comment by larryzhao** [comment]
Hi, 对的, 我们测试下来用ipad mini可以登录, 能具体说明一下么你点了「使用weibo登录」的按钮之后是什么状况导致您无法登录么?

**Comment by yangwenmai** [comment]
晚上在家测试可以正常登陆，只是非常慢，一方面是我的网络可能本来不是很好，另外一个可能是验证太慢太卡太耗时了。谢谢你的回复。

**Comment by larryzhao** [comment]
@yangwenmai  :D
