### ISSUE TITLE
关于简书的中文字体

### ISSUE THREAD

**Issue by appcell** [larryzhao/jianshu.io#19]
我自己是个前端 只能从前端的角度说一些关于设计的看法 有搞设计的朋友请大方地指出我的错误

---
## 字号的选择

在chrome 28 + 1920*1080分辨率下，简书阅读的正文字体采用13px。大多数中文字体都是以偶数像素点为基准设计的，例如宋体作为像素字只在12px下显示良好，雅黑针对14px作了优化。如今在chrome和新版IE（IE10/11）以及firefox或者safari下，11px和13px的宋体会按12px来显示，但较老版本的IE就只能显示成11px或13px的宋体，也就是说会模糊。而且显示成12px的13px宋体和原本就是12px的宋体的letterspacing有区别，前者比较大。在行间距不是很大的情况下，这会对阅读造成一定影响。行间距和字距，其中总有一个需要调整。
同样由于中文字体基于偶数像素点设计的原因，简书的文章标题（H4）采用17.5px，在此时的显示也不那么良好。Win下有严重锯齿，即使在Mac下17.5px这个值也很难出色渲染。建议换成18px。网站其余模块的字号如果出现类似情况也建议修改。

---
## 字体的选择

简书阅读的专栏标题采用楷体（粗体），文章标题（H4）采用微软雅黑（粗体），正文采用宋体。简书写作的正文和标题都采用宋体。我分别说一下个人对这几种字体的看法。
- **楷体（粗体）** 单就楷体这种字体而言，它并不适合作为网页字体使用——楷体是一种艺术字，不该作为内容字使用。另外楷体是没有粗体的，它的strong是伪粗体。不论Win还是MacOS对伪粗体的渲染都不好，这就导致了显示时无可避免的锯齿和模糊，加粗以后整个字体的结构都很奇怪。
- **雅黑（粗体）** 与楷体不同，雅黑和宋体都是内容字。雅黑的制造目的之一就是为了显示正文，因此专门对14px做了优化。雅黑也是有自带粗体的。但雅黑为了优化正文显示，在字号过大时字体的间架结构不是很优雅，加粗后更会有严重模糊。截图如下：  
  ![image](https://f.cloud.github.com/assets/1201164/867124/08872554-f6d5-11e2-9242-2b735219109d.png)  
  如图，字体轮廓模糊不说，“喧嚣”二字很多笔画都黏在一起分不清楚。在标题字的选择上，较细的雅黑或者华文细黑（不论粗还是细）都会更好一些，这方面可以参考一下Metro或者iOS的设计规范文档。
- **宋体** 宋体是最常用的中文衬线字，它的特殊之处在于个别字号（12px/14px/16px，其中16px已经开始有衬线的感觉了，要谨慎使用）的宋体会被渲染成像素字。其实基本可以这几个字号的宋体和其余字号的宋体看作两个字体。 由于衬线的缘故，非12px/14px/16px的宋体都会显得难以分辨（衬线太细），因此在写作和阅读时如果字体过大，用宋体当作正文字并不是个好选择。

---
## 一些细节

比如专题推荐页面或者各个小功能块的字体行间距，Georgia特有的数字怎么和平稳规整的中文混排（或者是不是该使用Georgia这么个有特色的字体）…字体虽然小，但对体验的影响很大，可以参考一下一些大公司的设计。

**Comment by linlis** [comment]
首先很感谢你的建议，未来我们会增加黑体系字体的设置，以满足喜欢黑体系字体的用户。

好奇怪啊，我们征文阅读字体从来没有用过 13px 嘛，我们现在是 18px 呀。相应的，h1-h6 都是大于 18px 的。

楷体只是不适合作为正文字体罢了，楷体作为简书的文章的标题字体非常适合，效果也很好，也很创新，无论是 win 还是 mac ox 的渲染效果都很好，这点我的意见与你正好相反。

雅黑的问题我们再调研一下看看，之前的印象中，win 下大字号的粗体，雅黑的表现是很不错的。

你对宋体不适合正文字体我也持保留意见，我认为在大字号下，适合做正文字体，不过这也是各人入各眼了，一般 IT 人事确实不喜欢宋体。

**Comment by appcell** [comment]
是我搞错了，13px那个是推荐页面的正文
截图说明。win下楷体：
![qq20130729135938](https://f.cloud.github.com/assets/1201164/869839/16e36752-f815-11e2-816f-590fc0f32471.png)
win下18px宋体：
![image](https://f.cloud.github.com/assets/1201164/869841/368f304a-f815-11e2-9e25-adb7eaeb348c.png)

简书写作：
正在编辑文章的标题：
![image](https://f.cloud.github.com/assets/1201164/869845/9ef8daf0-f815-11e2-977a-aac689d557f6.png)

正文部分的文章标题：
![image](https://f.cloud.github.com/assets/1201164/869850/ea6aca52-f815-11e2-93d7-5244a576b5da.png)

**Comment by linlis** [comment]
OK，我们研究下。

**Comment by constantinexue** [comment]
非常赞同 @appcell 的观点，我也是来说字体这个事情的。在iPhone的Safari上面，英文数字也表现不佳。奇怪的地方是简书有字体选择的选项，却不是针对全部页面的。我用mac和windows。宋体字表现不算好，建议font-family先把雅黑啥的放到第一，宋体第二吧。如果再保证英文的字体，试试Bootstrap的效果，加上黑体：

```
@font-family-sans-serif:  "Helvetica Neue", Helvetica, Arial, "Microsoft Yahei", sans-serif;
```

**Comment by yangchi** [comment]
出于好奇google了一下“简书 楷体”，然后看到了这个thread。我觉得文章页面用楷体做标题字体属于“值得商榷”。但是简书网站首页右侧主体部分的文章列表也用楷体显示文章标题就有点不当了。因为这些文章标题在这里其实不是标题，而是内容。所以不应该把标题字体的规则用在上面。依然使用楷体的结局就是屏幕上有大量楷体存在，略不舒服。比如在15存的rMBP上首页会有4-5组这样的楷体标题。而且因为明显比标题下面的文章excerpt字号要大，以及看文章列表的时候本来视线就集中在标题，所以真的很有满屏楷体的错觉和不适感。

**Comment by beyondskyway** [comment]
现在貌似都是用微软雅黑，为什么忽然换了？有什么原因么？

**Comment by larryzhao** [comment]
@beyondskyway 您是指您看到简书现在是什么字体？我们查一下，同时能提供一下您的系统和浏览器么？

**Comment by beyondskyway** [comment]
@larryzhao 是的，查阅字体阅读体验时翻到这个，记得之前简书是宋体，但是现在都雅黑（win10+chrome）

**Comment by larryzhao** [comment]
@beyondskyway 我们后来改成可以设置了，您可以看左侧边栏下面有个`A` icon，点击可以切换衬线体和非衬线体
