### ISSUE TITLE
分享到 twitter 

### ISSUE THREAD

**Issue by linlis** [larryzhao/jianshu.io#2]

**Comment by vincent4j** [comment]
我个人比较喜欢将好的文章发布到tumblr用于收藏，所以建议加个email分享，最好是email全文分享；为了推广，可以在邮件正文最顶部加上“原本出处”的声明。

话说，不知道这种需求是否大众化。

**Comment by linlis** [comment]
@vincent4j 你可以再开个email 分享的 issue ：）

**Comment by vincent4j** [comment]
@linlis  copy， new了一个 #3
