### ISSUE TITLE
建议把简书的英文去掉

### ISSUE THREAD

**Issue by jingkaihe** [larryzhao/jianshu.io#23]
网站中英文<del>加载</del>夹杂很奇怪，建议都改成中文

**Comment by larryzhao** [comment]
中英文加载您指的是?

**Comment by jingkaihe** [comment]
类似于 write something, collections, updated about 18 hours ago 之类的东东～

感觉也是面向国内用户的吧，如果不做 i18n 不如全盘中文～

当然只是个人建议

**Comment by larryzhao** [comment]
Hi, jaxi, 你看到英文的话应该是你浏览器设置是英文或者你用户设置里是英文的, 你可以注册用户然后在用户设置里调整成中文就可以了。
