### ISSUE TITLE
帐号如何绑定多个SNS？

### ISSUE THREAD

**Issue by evilexist** [larryzhao/jianshu.io#30]
ID是用新浪微博绑定的，之前的登陆过程中好像用douban和QQ误登陆过，现在在新浪微博的帐号里绑定豆瓣会提示已经绑定过，如何解除？

**Comment by larryzhao** [comment]
你之前用douban和qq误登录的时候设置过email么?

**Comment by evilexist** [comment]
试了一下再次用豆瓣登录，进入初始设置，应该是没有成功绑定的吧？

**Comment by larryzhao** [comment]
进入初始设置的话, 你在初始设置里面点 Sign Out 就好了, 然后再去你想要绑定豆瓣的用户里面去绑定, 就好了

**Comment by evilexist** [comment]
多谢~这个办法确实可行.就是有些隐蔽。
