### ISSUE TITLE
简信的默认高度可否自适应？

### ISSUE THREAD

**Issue by evilexist** [larryzhao/jianshu.io#32]
我的显示器分辨率是1440x900，台式机。

简信的默认长度可能有些过了，在写完简信后不知道怎么发送。
因为看不到任何的按钮。当然，看了半天主意到了旁边的滚动条，可是我双手都在键盘上诶...也许台式机不是简书的用户群？

现在的默认高度可能高了一些，简信大概真的不会写太多字的吧。

**Comment by larryzhao** [comment]
台式机一定是我们的用户群请放心, 这个我们试试看调整一下按钮的位置看看
