### ISSUE TITLE
功能開發

### ISSUE THREAD

**Issue by coralfs** [larryzhao/jianshu.io#4]
1，建議添加站內搜索功能，不然要想找一位作者或某一篇文章需要耗費大量的時間去挨個瀏覽。隨著用戶的增加，這必然會帶來困擾。
2，建議添加更多分享按鈕，比如twitter，facebook等，用戶可以方便地分享好文章，也無形中為網站做了推廣，何樂而不為？謝謝！

**Comment by linlis** [comment]
@coralfs  谢谢您的建议。
1. 暂时您可以打开 Google，在搜索栏输入「 site:http://jianshu.io 搜索内容 」来进行搜索，当然这是权宜之计。
2. 在计划中。

**Comment by larryzhao** [comment]
1. 站内搜索我们暂时添加了搜索框使用 Google 站内搜索, 我们独立的搜索正在建设中. 请期待。
2. 分享至 Facebook, Twitter 功能已上线。

**Comment by coralfs** [comment]
……
在 2013-7-1 下午10:10，"Larry Zhao" notifications@github.com写道：

**Comment by larryzhao** [comment]
@coralfs 肿么了?

**Comment by coralfs** [comment]
不好意思，手机出了点问题，自动发送的。打扰您了，抱歉T_T

**Comment by larryzhao** [comment]
@coralfs 哈哈, 米问题
