### ISSUE TITLE
喜欢文集的BUG

### ISSUE THREAD

**Issue by forecho** [larryzhao/jianshu.io#42]
自己可以喜欢自己的文集，虽然没有任何效果，**但是会发给我一封邮件说我的文集被喜欢了，**然后那个喜欢的人还是我自己。
在我喜欢的文件里面也没找到任何文集。

**Comment by larryzhao** [comment]
我试验了一下, 喜欢了之后会在「我喜欢的文集」里面出现呀, 你的没有么?

**Comment by forecho** [comment]
@larryzhao 咦，现在可以了，之前对自己的文集点喜欢是没有反应的，但是有收到邮件。当时我试了2、3遍了的。
为什么自己能喜欢自己的文集呢？

**Comment by larryzhao** [comment]
我们自己也可以喜欢自己的文章哈，这点我们没有限制，大家都可以喜欢。

对于文集来说，喜欢就相当于关注，喜欢了之后你会在自己的动态里面收到文集相关的动态，不过现在主要也是你在哪个文集里面写了什么新的文章啦。
