### ISSUE TITLE
列表模式与编辑模式间切换，由于cache不当导致的文章编辑内容丢失的问题

### ISSUE THREAD

**Issue by shinemoon** [larryzhao/jianshu.io#43]
新年快乐——不管看不看得到，趁现在睡不着，闲的蛋疼肚子饿的时候赶快写下这个让我曾经丢失过好几次文章内容的问题……

chrome下进行文章编辑（仅试过Markdown模式），如下场景：

当先打开写作模式，开始写文章，写了一半之后，保存（Save1），esc到文章列表，这时我忽然心血来潮想改，就顺手直接在文章列表模式中的右侧面板中进行文章编辑又写了一段，保存（Save2）。

之后，我又（好吧）心血来潮，想写的更专业一点，于是在没关闭的情况下，点击「写作模式」进入到写作页面想改点东西，这个时候，就会发现，页面内容是显示的Save1的内容，假如我反应过来了的话，那当然淡定的一个ctrl+R，刷新下，就会发现Save2的内容被读入了（不过这个时候的UI也乱了，编辑框变成了很短的一个长度，需要scroll来看内容）；

可是，如果当时没注意，直接开始写字，导致自动保存，或者换个情况下，脑子一抽，顺手ctrl+S的话，那么Save2的内容就白写了——我自己犯过好多次这个错误，郁闷死了。

这个问题同样会出现在「列表模式」和「预览模式」之间切换的时候，简单讲，就是在曾经在「写作」和「预览」模式下写作并且没有关闭过页面，那么在「列表模式」下做的修改，是无法在同页面再次跳转的「写作」和「预览」模式中显示的，

虽然是个可以手动规避的问题，但是，真的，对于有在列表模式顺手修改文章的懒人来说，这种体验是摧毁性的，特别是新用户……

望解决。

**Comment by shinemoon** [comment]
补充一下，这个现象不是100%必现，可能还有别的触发点之类，但是几率非常高，至少我来回切换尝试，5次里可以出现3次左右。

**Comment by larryzhao** [comment]
收到, 我来看, 感谢啊

**Comment by shinemoon** [comment]
:) 这大过年的，哈哈哈哈

-----原始邮件-----
发件人: "Larry Zhao" notifications@github.com
发送时间: ‎2014/‎1/‎29 11:42
收件人: "larryzhao/jianshu.io" jianshu.io@noreply.github.com
抄送: "shinemoon" shinemoon@gmail.com
主题: Re: [jianshu.io]=?UTF-8?Q?_=E5=88=97=E8=A1=A8=E6=A8=A1=E5=BC=8F=E4=B8=8E=E7=BC=96=E8=BE=91=E6=A8=A1=E5=BC=8F=E9=97=B4=E5=88=87=E6=8D=A2=EF=BC=8C=E7=94=B1=E4=BA=8Ecache=E4=B8=8D=E5=BD=93=E5=AF=BC=E8=87=B4=E7=9A=84=E6=96=87=E7=AB=A0=E7=BC=96=E8=BE=91=E5=86=85=E5=AE=B9=E4=B8=A2=E5=A4=B1=E7=9A=84=E9=97=AE=E9=A2=98?==?UTF-8?Q?_=28#43=29?=

收到, 我来看, 感谢啊

**Comment by larryzhao** [comment]
Hi, @shinemoon 我看了一下, 我估计是你切换速度比较快, 我之前的保存间隔设置的是600ms, 到了600ms 才会被 persist 到 js object 然后 persist 到服务端。

我现在修正了，一下，Markdown 部分会实时 persist 到 js object 这样你切换肯定不会出现之前的问题了。不过 RichText Editor 现在还会有微小的延时，不过肯定比600ms要小，而且我们自己正在重新开发 RichText编辑器，就快要完成了，到时候就ok啦.

正在部署中.

**Comment by shinemoon** [comment]
高效丨乛一乛丨一丨

-----原始邮件-----
发件人: "Larry Zhao" notifications@github.com
发送时间: ‎2014/‎1/‎29 13:56
收件人: "larryzhao/jianshu.io" jianshu.io@noreply.github.com
抄送: "shinemoon" shinemoon@gmail.com
主题: Re: [jianshu.io]=?UTF-8?Q?_=E5=88=97=E8=A1=A8=E6=A8=A1=E5=BC=8F=E4=B8=8E=E7=BC=96=E8=BE=91=E6=A8=A1=E5=BC=8F=E9=97=B4=E5=88=87=E6=8D=A2=EF=BC=8C=E7=94=B1=E4=BA=8Ecache=E4=B8=8D=E5=BD=93=E5=AF=BC=E8=87=B4=E7=9A=84=E6=96=87=E7=AB=A0=E7=BC=96=E8=BE=91=E5=86=85=E5=AE=B9=E4=B8=A2=E5=A4=B1=E7=9A=84=E9=97=AE=E9=A2=98?==?UTF-8?Q?_=28#43=29?=

Hi, @shinemoon 我看了一下, 我估计是你切换速度比较快, 我之前的保存间隔设置的是600ms, 到了600ms 才会被 persist 到 js object 然后 persist 到服务端。
我现在修正了，一下，Markdown 部分会实时 persist 到 js object 这样你切换肯定不会出现之前的问题了。不过 RichText Editor 现在还会有微小的延时，不过肯定比600ms要小，而且我们自己正在重新开发 RichText编辑器，就快要完成了，到时候就ok啦.
正在部署中.

**Comment by larryzhao** [comment]
哈哈, 我反正不修这个也是做别的

**Comment by shinemoon** [comment]
血汗公司

-----原始邮件-----
发件人: "Larry Zhao" notifications@github.com
发送时间: ‎2014/‎1/‎29 17:04
收件人: "larryzhao/jianshu.io" jianshu.io@noreply.github.com
抄送: "shinemoon" shinemoon@gmail.com
主题: Re: [jianshu.io]=?UTF-8?Q?_=E5=88=97=E8=A1=A8=E6=A8=A1=E5=BC=8F=E4=B8=8E=E7=BC=96=E8=BE=91=E6=A8=A1=E5=BC=8F=E9=97=B4=E5=88=87=E6=8D=A2=EF=BC=8C=E7=94=B1=E4=BA=8Ecache=E4=B8=8D=E5=BD=93=E5=AF=BC=E8=87=B4=E7=9A=84=E6=96=87=E7=AB=A0=E7=BC=96=E8=BE=91=E5=86=85=E5=AE=B9=E4=B8=A2=E5=A4=B1=E7=9A=84=E9=97=AE=E9=A2=98?==?UTF-8?Q?_=28#43=29?=

哈哈, 我反正不修这个也是做别的
