### ISSUE TITLE
可定制化首页

### ISSUE THREAD

**Issue by unionx** [larryzhao/jianshu.io#44]
简书首页是否可以做成可定制化的？稍微学习一下可以屏蔽掉某类主题的文章

**Comment by larryzhao** [comment]
不错的建议, 我们会考虑给用户对首页文章列表一定的设置的余地，不过现在如果提供这个功能也只能是设置屏蔽某作者、屏蔽某专题，这样的过滤。

我想请问一下，您说的「稍微学习一下」是指什么呢?

**Comment by unionx** [comment]
就是机器学习吧，用点简单的贝叶斯分类。

比如我根据文章里的关键词（或者作者自己加的tag）学习分类，再假设首页的文章可以点击“不再显示”，一段时间之后就能发现这个用户不喜欢读某一类的文章，然后就不显示这些文章，或者把这些文章放到比较后面的位置显示。
