### ISSUE TITLE
关于阅读、导出的一些问题以及建议

### ISSUE THREAD

**Issue by ghost** [larryzhao/jianshu.io#45]
在阅读时，感觉字体较大，（较大的宋体使人看着不太舒服）
ps. 14寸笔记本，可能是因为我屏幕尺寸的问题。
以后会不会支持文章导出、备份之类的功能。例如：导出和其他博客系统相关的格式文件。

**Comment by larryzhao** [comment]
首页字体我们这两天有过改动，文章字体我们认为现在是很好的选择，宋体在小字体情况下更难以表现他的美感。我们也提供了黑体，您可以尝试，在文章阅读界面的右上角，点击A按钮就可以设置了。

现在文章已经可以保存了，功能在设置里。我们以后会做自动备份到相应的网站, 例如 dropbox 等等。不过暂时没有计划做导出其他博客系统相关的格式文件。
