### ISSUE TITLE
Markdown下url链接自动转换？

### ISSUE THREAD

**Issue by shinemoon** [larryzhao/jianshu.io#47]
不知道是否新版引入的功能，会自动将http开头的文本转换成超链接，个人觉得，作为markdown模式下，这种处理不太合适——特别是，现在是以空格区分的？即如果是引号扩起的'http://url'，和后面的文本没有隔开，就会整个变成一个超链接，这，太不优雅了吧？

**Comment by larryzhao** [comment]
是这样实现的，这方面其实我们是遵循的 Github 的做法诶
