### ISSUE TITLE
提个feature

### ISSUE THREAD

**Issue by cobola** [larryzhao/jianshu.io#53]
我有个朋友
觉得你们的网站很好
想让copy一个 ⊙﹏⊙b汗 
## 这怎么行！

我想 用 collection 的这个页面

绑定 自己的域名 全程不出现简书字样 （也就是和贵站风格一样 但又完全看不到贵站的名字，后台之类的用同一套平台）

这种奇怪的需求 你们觉得怎么样？

**Comment by larryzhao** [comment]
这种奇怪的需求听起来跟我们关系好像不大诶
