### ISSUE TITLE
iphone下登录以后，看下一篇文章不会保存登录状态？#bug#

### ISSUE THREAD

**Issue by shubo83** [larryzhao/jianshu.io#54]

**Comment by larryzhao** [comment]
我这里测试是正常的哈, 能详细描述一下么?

**Comment by shubo83** [comment]
![1 pic](https://cloud.githubusercontent.com/assets/3070621/3113247/3839f38c-e6d3-11e3-9ef8-c74f44ef062b.jpg)
哦 是点了喜欢 然后一直无响应 再刷新就没有登录了

**Comment by larryzhao** [comment]
我刚刚实验了一下可以诶, 你是每次都不行么?
