### ISSUE TITLE
简书有 API 开放吗？

### ISSUE THREAD

**Issue by liyong03** [larryzhao/jianshu.io#56]
我想为简书做一款 iPhone 客户端

**Comment by larryzhao** [comment]
暂时还没有开放 API, 开放 API 的时候我们会通知你哈

**Comment by liyong03** [comment]
能问一下有这个计划吗，大概什么时候？

**Comment by larryzhao** [comment]
暂时还木有时间表

**Comment by ldong** [comment]
羊年了, @larryzhao 給個update吧.

**Comment by MingStar** [comment]
+1 有同样的需求

**Comment by RishonLi** [comment]
其实更期待通过「简书API」把简书与记事本打通。想象下打开「Sublime Text」写上几行文字，快捷键保存，大家就可以在简书网站上查看到。

**Comment by kyle18th** [comment]
期待,看了其中一个专题,很喜欢,但是找不到api.想做出来小范围使用

**Comment by ldong** [comment]
猴年了,  @larryzhao 給個 update 吧.

**Comment by moJiXiang** [comment]
api有测试的吗

**Comment by larryzhao** [comment]
@moJiXiang @ldong 简书暂时没有开放 API 的计划

**Comment by fuermosi777** [comment]
希望可以开放API

**Comment by jhjwind** [comment]
+1

**Comment by SeniorZhai** [comment]
简单的给自己post一些文章也好

**Comment by lindexi** [comment]
如果可以让第三方开发者开发的gitbook.io的文章导入简书就好

**Comment by wq163** [comment]
我的原则是凡是不支持metaweblog api的一律不用

**Comment by gaoios** [comment]
我跟一下，什么时候开放Api呀

**Comment by geosmart** [comment]
jianshu什么时候开放AP可以提交博客？有知道别的好的平台支持API的吗？

**Comment by wzshuang** [comment]
狗年了, @larryzhao 給個 update 吧.

**Comment by larryzhao** [comment]
简书暂时没有开放 API 的计划

**Comment by yee94** [comment]
我想将我git中写的文章自动update到简书发布。没有可用的接口。好烦

**Comment by lindexi** [comment]
@xiaobebe [简单搭建自己的博客](https://lindexi.gitee.io/post/%E7%AE%80%E5%8D%95%E6%90%AD%E5%BB%BA%E8%87%AA%E5%B7%B1%E7%9A%84%E5%8D%9A%E5%AE%A2.html )

**Comment by LinuxSuRen** [comment]
简书为啥不开发 API 呢？

**Comment by Yaanco** [comment]
猪年了， @larryzhao 给个update吧

**Comment by exit-k0a1a** [comment]
哇，这都多少年了，就不能开发个update的接口吗？我只是想把我的blog文章同步过来啊……

**Comment by zcfan** [comment]
我只是不想一篇文章在 ia writer 写完了还要一个一个图片拖到网页编辑器里上传。。。找了这么一圈，国内居然没有一个平台能支持。。。

**Comment by Barneybook** [comment]
如果開放API可以帶來收入，我相信應該早做了

**Comment by RishonLi** [comment]
> 如果開放API可以帶來收入，我相信應該早做了

简书的模式不是服务作者，来在读者中收费吗？这种服务作者的api不是很有价值吗？

**Comment by martinadamsdev** [comment]
@larryzhao 个人开发者可以申请 KEY 吧。比如，付费的别人的文章就不能乱搞了。
