### ISSUE TITLE
新建笔记/新建笔记本后，鼠标自动悬停在标题位置

### ISSUE THREAD

**Issue by nicolasmei** [larryzhao/jianshu.io#6]

**Comment by larryzhao** [comment]
您是指光标位置是吧?

**Comment by nicolasmei** [comment]
对的，就是指光标位置。

发自我的 iPad

在 2013-6-5，14:51，"Larry Zhao" notifications@github.com 写道：

**Comment by larryzhao** [comment]
@nicolasmei 好的, 这个也的确是我们可以改进的地方, 谢谢
