### ISSUE TITLE
简书如何实现的邀请好友获1元钱

### ISSUE THREAD

**Issue by biebg** [larryzhao/jianshu.io#60]
问题是在， 一个应用通过连接下载注册的时候，如何得知是通过谁分享的连接来下载注册的应用.
android 还可以大概了解，但IOS app 想不明白， 如果方便回答的话，请回答一下。 如果issue 在这里不合适请关闭，或者给个邮件地址。非常感谢。

**Comment by larryzhao** [comment]
使用 ip 判断，的确会出现不准的情况，很早之前就已经下线
