### ISSUE TITLE
“我的主页”右侧三个标签页标识问题

### ISSUE THREAD

**Issue by heartstrings22** [larryzhao/jianshu.io#62]
进入页面后，默认选中**最新动态**标签页，在点击**最新动态**或**热门文章**后，原先**最新动态**的选中标识未移除，导致标识重复。
虽然不是大的bug，但是细节问题还是要注意的~ X0

**Comment by heartstrings22** [comment]
如果能加入简书，那我来修复这个bug~ X0

**Comment by mypopcs** [comment]
简书如果能出一个PC客户端就好了，至少chrome插件也不错

**Comment by MxABC** [comment]
对的，为知笔记 客户端已经开源了，简书 可以根据这个代码修改一下形成自己的客户端，然后就完美了
