### ISSUE TITLE
是时候重提开放API这事儿了

### ISSUE THREAD

**Issue by Stargazer1492** [larryzhao/jianshu.io#64]
每个人有自己写blog的工具和环境，没必要限制在简书自己的平台上。或者说，简书的编辑器适合非技术写手。开放了api，让社区为你们搞一个client，随意使用自己的markdown编辑器，然后推送到简书上，这样能争取更多用户，何乐而不为。

**Comment by bugparty** [comment]
是啊，为啥不给开。不开不清真

**Comment by leesf** [comment]
同问，什么时候可以开放API

**Comment by DongYuHui** [comment]
已经 18 年了，我也来重提一下，希望能够开放 API

**Comment by bugparty** [comment]
要不咱们自己实现吧

**Comment by larryzhao** [comment]
现在不考虑开放API

**Comment by bugparty** [comment]
直接用浏览器模拟，然后开源打官方脸
