### ISSUE TITLE
对文章的长度限制有点不爽

### ISSUE THREAD

**Issue by CoryXie** [larryzhao/jianshu.io#65]
我偶尔会有比较长的文章，因为是翻译一些书籍或者技术规范，想尽量把一章的内容放在一篇文章中，但是当文章比较长的时候，就会发现每次保存都弹出一个JS的对话框，提示让分段保存，但是实际上这些多出来的内容还是保存了（几次测试发现的）。能不能把长度限制增加，不知现在的限制是多少，然后不要老是弹出那种提示了，我用cmd markdown写同样的文章就没问题。

**Comment by larryzhao** [comment]
1. 肯定会保留文章长度限制，不会支持无限长度，外面一章可能是200字也可能是天龙八部的一章。
2. 对于提示限制之后超限制的内容，请自行保留好，现在保存了的不能保证一直存在
