### ISSUE TITLE
简书会添加每日活跃度这样的总结日历吗？

### ISSUE THREAD

**Issue by moenn** [larryzhao/jianshu.io#66]
![image](https://user-images.githubusercontent.com/17309322/35194024-d5142c70-fee6-11e7-8ae7-d1746a6b1697.png)

类似 github 的这种日历，当用户新发布一篇文章或发布旧文的更新时就用颜色填充当日的小框框，也许打赏其他作者的文章的行为也可以计算在内。

可以给用户写新文和修改旧文增加动力。 @larryzhao

**Comment by larryzhao** [comment]
这提议不错，我们会考虑
