### ISSUE TITLE
简书会添加‘踩’文章的功能吗？

### ISSUE THREAD

**Issue by moenn** [larryzhao/jianshu.io#67]
在简书上，一篇文章的质量可能是用这些数据计算的：  阅读人数，♥数量，收藏量，评论量，打赏量。

那么为什么不出一个'踩'文章的功能，并把它作为一个计算文章质量的因素。如果不喜欢一篇文章，使用‘踩’或‘没有帮助’来降低它的热度，使它更不可能出现在**发现**一栏里。

这样做能不能提高**发现**一栏里出现的文章的质量？

**Comment by larryzhao** [comment]
有考虑，暂时不会提供
