### ISSUE TITLE
作者点击「笔记」按钮后的跳转

### ISSUE THREAD

**Issue by shinemoon** [larryzhao/jianshu.io#9]
如果在「简书·社」对自己的文章进行阅读，此时点击右上角按钮（笔图标），会进行跳转，但是，跳转页面（或者说光标吧）仅仅只是停留在第一个目录的第一篇文章，而并非是跳转到之前阅读的这篇文章。

从我本人的操作期望上，这样的操作，其实多半是为了编辑我所读到的这篇文章，有无可能做些改进，或者例如增加「编辑此文」的快速入口？

**Comment by larryzhao** [comment]
恩, 这个正在做, 即将推出啊~, 呵呵
